# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'

steps:
- template: 'Templates/Build Net Core.yml'
  parameters:
    buildConfiguration: '$(buildConfiguration)'

- template: 'Templates/Pack Net Core.yml'
  parameters:
    projects: '**/NetCoreEntityFramework.csproj'
    buildConfiguration: '$(buildConfiguration)'
    skipBuild: true
    skipInstall: true

- task: NuGetAuthenticate@0
  inputs:
    nuGetServiceConnections: 'NuGet Feed'

- task: NuGetCommand@2
  inputs:
    command: 'push'
    packagesToPush: '$(Build.ArtifactStagingDirectory)/**/*.nupkg;!$(Build.ArtifactStagingDirectory)/**/*.symbols.nupkg'
    nuGetFeedType: 'external'
    publishFeedCredentials: 'NuGet Feed'