global using AutoFixture.NUnit3;
global using Microsoft.EntityFrameworkCore;
global using Monstarlab.EntityFramework.Extension.Enums;
global using Monstarlab.EntityFramework.Extension.Models;
global using Monstarlab.EntityFramework.Extension.Repositories;
global using Monstarlab.EntityFramework.Extension.Tests.Mocks;
global using NUnit.Framework;
global using System;
global using System.Collections.Generic;
global using System.Linq;
global using System.Threading.Tasks;
global using TestContext = Monstarlab.EntityFramework.Extension.Tests.Mocks.TestContext;
