global using AutoFixture.NUnit3;
global using Microsoft.EntityFrameworkCore;
global using Nodes.NetCore.EntityFramework.Enums;
global using Nodes.NetCore.EntityFramework.Models;
global using Nodes.NetCore.EntityFramework.Repositories;
global using Nodes.NetCore.EntityFramework.Tests.Mocks;
global using NUnit.Framework;
global using System;
global using System.Collections.Generic;
global using System.Linq;
global using System.Threading.Tasks;
global using TestContext = Nodes.NetCore.EntityFramework.Tests.Mocks.TestContext;