name: Publish to NuGet

on:
  push:
    branches:
    - master
    paths:
    - 'Monstarlab.EntityFramework.Extension/**'

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
      
    - name: Install dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --configuration Release --no-restore

    - name: Generate NuGet package
      run: |  
        cd Monstarlab.EntityFramework.Extension
        dotnet pack --configuration Release --output out --no-build  

    - name: Push generated package to NuGet.org
      run: dotnet nuget push **.nupkg --skip-duplicate --no-symbols true --source https://api.nuget.org/v3/index.json --api-key ${{ secrets.NUGET_API_KEY }}
